version: '3.8'

services:
  hotel-postgres:
    image: 'postgres:latest'
    container_name: hotel-postgres
    environment:
      POSTGRES_DB: ${HOTEL_POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - online-traveling-network
    ports:
      - '${HOTEL_POSTGRES_PORT}:5432'
  
  hotel-service:
    build:
      context: ./hotel
    container_name: hotel-service
    ports:
      - "8081:8080"
    environment:
      - ENV=production
      - TZ=Asia/Tehran
      - HOTEL_CONFIG_PATH=/app/config.json
      - KAFKA_BROKER=kafka:9092
    networks:
      - online-traveling-network
    restart: unless-stopped
    depends_on:
      - hotel-postgres
    volumes:
      - ${HOTEL_CONFIG_PATH}:/app/config.json

networks:
  online-traveling-network:
    driver: bridge
