FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
# RUN GO111MODULE=on GOPROXY=https://goproxy.cn,direct go mod download
RUN go mod download
COPY . .
# RUN GO111MODULE=on GOPROXY=https://goproxy.cn,direct go build -o server ./cmd/webApp/main.go
RUN go build -o server ./cmd/webApp/main.go

FROM alpine:latest
RUN apk --no-cache add tzdata ca-certificates
ENV TZ=Asia/Tehran
# RUN apk --no-cache add ca-certificates
WORKDIR /app/
COPY --from=builder /app/server .
# COPY --from=builder /app/certs .
EXPOSE 8080
CMD ["./server"]