FROM docker.arvancloud.ir/golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server ./cmd/webApp/main.go

FROM docker.arvancloud.ir/alpine:latest
RUN apk --no-cache add tzdata
ENV TZ=Asia/Tehran
RUN apk --no-cache add ca-certificates
WORKDIR /app/
COPY --from=builder /app/server .
COPY --from=builder /app/certs .
EXPOSE 8081
CMD ["./auth"]