
db:
  host: "vehicle-postgres"
  port: 5432
  database: "vehicle"
  schema: "public"
  username: "admin"
  password: "12345"

server:
  httpPort: 8085
  secret: "your_secret_key"
  authExpMin: 15
  authExpRefreshMin: 60
  rate_limit_max_attempt: 5
  ratelimit_time_period: 60
